'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegistroPacientes

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''regPacTxbNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regPacTxbNombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''regPacDDLHab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regPacDDLHab As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DsListaHabitaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DsListaHabitaciones As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DsOcuparHabitacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DsOcuparHabitacion As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RegPacDDLMed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegPacDDLMed As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DsListaMedicos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DsListaMedicos As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''RegPacBtnRegistrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegPacBtnRegistrar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DsRegistroPaciente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DsRegistroPaciente As Global.System.Web.UI.WebControls.SqlDataSource
End Class
